- name: Query OMDb API and create Excel
  hosts: ditra
  gather_facts: false
  vars_files:
    - vars/secrets.yml
  vars:
    search_term: "Matrix"
    output_file: "movies_results.xlsx"
    log_file: "ansible_api_excel.log"
    ts: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%SZ') }}"

  tasks:
    - name: Connectivity and API Process
      block:
        - name: Check host connectivity
          ansible.builtin.wait_for_connection:
            timeout: 10
          register: connectivity_check

        - name: Log Host Reachable
          ansible.builtin.shell: |
            echo "[{{ ts }}][SUCCESS] Host {{ inventory_hostname }} is reachable" >> "{{ log_file }}"
          delegate_to: localhost
          changed_when: false

        - name: Query OMDb API
          ansible.builtin.uri:
            url: "http://www.omdbapi.com/?apikey={{ omdb_api_key }}&s={{ search_term }}"
            return_content: true
          register: api_res
          delegate_to: localhost

        - name: Validate API Response
          ansible.builtin.assert:
            that:
              - api_res.json.Response == "True"
            fail_msg: "API Error: {{ api_res.json.Error | default('Unknown') }}"

        - name: Save API data to temp file
          ansible.builtin.copy:
            content: "{{ api_res.json | to_json }}"
            dest: "/tmp/api_data.json"
            mode: "0644"
          delegate_to: localhost

        - name: Create Excel file
          ansible.builtin.command: "python3 ./files/create_excel.py /tmp/api_data.json {{ output_file }}"
          delegate_to: localhost
          register: excel_creation
          changed_when: excel_creation.rc == 0

        - name: Remove temp file
          ansible.builtin.file:
            path: "/tmp/api_data.json"
            state: absent
          delegate_to: localhost

        - name: Log Success
          ansible.builtin.shell: |
            echo "[{{ ts }}][INFO] Host {{ inventory_hostname }} - Success: {{ search_term }} -> {{ output_file }}" >> "{{ log_file }}"
          delegate_to: localhost
          changed_when: false

      rescue:
        - name: Log Failure
          ansible.builtin.shell: |
            echo "[{{ ts }}][ERROR] Host {{ inventory_hostname }} - \
            {{ ansible_failed_task.name }}: \
            {{ ansible_failed_result.msg | default('Execution failed') }}" >> "{{ log_file }}"
          delegate_to: localhost
          changed_when: false
